### ISSUE TITLE
Error in `capture request header` example

### ISSUE THREAD

**Issue by cipriancraciun** [cbonte/haproxy-dconv#12]
In the section about `capture request header <name> len <length>`, at the end there is the following example:

    capture request header Host len 15
    capture request header X-Forwarded-For len 15
    capture request header Referrer len 15

The last line is wrong as the header name should be `Referer` (i.e. the misspelled version with a single `r` instead of the correct version with two `rr`).

(Later on in the documentation it is written "correctly" with a single `r`.)

**Comment by cbonte** [comment]
Hi, this is a typo that you should report directly to the haproxy mailing list.
If you can, please provide a patch which fixes the typo in doc/configuration.txt.

**Comment by cipriancraciun** [comment]
I've resubmitted it here: https://github.com/haproxy/haproxy/issues/46

**Comment by cbonte** [comment]
Hi again, this is not the official haproxy repository so it won't be addressed.

OK, I take the action and will provide the patch to the right destination.

**Comment by cipriancraciun** [comment]
Sorry for not looking into where to properly submit this issue, but I thought that this repository was maintained by one of the HAProxy developers.  I've then re-submitted the ticket to the `haproxy/haproxy` repository, because I saw that, although it was mentioned it is only a mirror, there were issues opened there (and some of theme were also closed).

Thanks for forwarding this minor bug to the ones responsible.  (It's not major, but for someone starting up he will have a hard time figuring out why his `Referer` header doesn't appear in the logs.)  :)

P.S.:  In my defense, I did a quick look through http://www.haproxy.org/ and after a cursory search for `bug`, `issue`, `ticket` or `submit` I found nothing useful, thus being in a hurry I've submitted it here.  (Perhaps you can also suggest them a more "visible" link to where submit tickets.)

**Comment by cbonte** [comment]
Example fixed upstream for 1.4/1.5/1.6/dev branches
