### ISSUE TITLE
Manual version 1.5.16

### ISSUE THREAD

**Issue by crosdorff** [cbonte/haproxy-dconv#13]
The following example is in de manual for version 1.5.16:

Append 'www.' prefix in front of all hosts not having it
http-request redirect code 301 location www.%[hdr(host)]%[req.uri] \
  unless { hdr_beg(host) -i www }

This goes wrong on two things:
1: req.ur should be capture.req.uri
2: http:// or https:// should be in front to avoid a redirect loop with a relative url.

http-request redirect code 301 location http://www.%[hdr(host)]%[capture.req.uri] \
  unless { hdr_beg(host) -i www }

**Comment by cbonte** [comment]
Hi, for haproxy-dconv, you should only report bugs/issues concerning the converter. For the documentation itself, it's preferable to report them to the haproxy mailing list directly.
Can you contact the mailing list ? Also, would you be able to provide a patch by yourself ?

**Comment by crosdorff** [comment]
I've send a patch to the mailing list. Thanks for pointing me in the right direction.
