### ISSUE TITLE
Small error in example

### ISSUE THREAD

**Issue by vvidic** [cbonte/haproxy-dconv#14]
Server name in this example should probably be `imap` rather than `mail`:

```
use-server imap if { req_ssl_sni -i imap.example.com }
server     mail 192.168.0.1:993 weight 0
```

becomes:

```
use-server imap if { req_ssl_sni -i imap.example.com }
server     imap 192.168.0.1:993 weight 0
```

**Comment by cbonte** [comment]
Please, can you report this upstream to the haproxy mailing list, and even better provide a patch ?
Here, I'll only treat issues concerning the converter itself, not the documentation content.
