### ISSUE TITLE
Convert management.txt

### ISSUE THREAD

**Issue by grobie** [cbonte/haproxy-dconv#15]
First of all, thank you so much for providing these docs. I'm a frequent user for years and they provide great value.

Since 1.6 the CSV and socket documentation seems to have moved from configuration.txt to management.txt in HAProxy. So far I usually open the 1.5 documentation to quickly look up some definition. It'd be very helpful to have access to a nicely rendered version of the 1.6 documentation for that. Is there any chance  you parse management.txt as well? I couldn't find it under https://cbonte.github.io/haproxy-dconv/management-1.6.html or linked in the menu.

**Comment by cbonte** [comment]
Yes I know, work is still in progress but I fail to find enough time to completely fix some issues. This is a question of weeks I think (I've already planned to provide a version with bugs if the remaining ones take me too long).

**Comment by cbonte** [comment]
At last, the work has begun. Everything is available from http://cbonte.github.io/haproxy-dconv/ or  https://cbonte.github.io/haproxy-dconv/

There are still some issues, but for now, I can close the one ;-)

**Comment by grobie** [comment]
Thanks a lot! As every user with routines, I'll need to get used to the new design first, but it's so great to have all the information available at one place. Kudos to your work!
