### ISSUE TITLE
Python dependencies not documented

### ISSUE THREAD

**Issue by odoucet** [cbonte/haproxy-dconv#18]
Hello Cyril,

You do not give Python dependencies to use your project. 

i found that at least Mako should be installed with pip.

Olivier

**Comment by cbonte** [comment]
Hello,
Some times ago, dependencies were listed on the wiki pages :
https://github.com/cbonte/haproxy-dconv/wiki/Python-Modules

I'm not fond of the wiki on github (at least for this project). I'll surely move those parts in the code branch itself (I intend to write a Dockerfile, for example), but I hardly find time currently. In the mean time, fill free to provide patches to improve this ;-)

**Comment by elijahbal** [comment]
Hi, this is resolved in the last pull-request

**Comment by cbonte** [comment]
Pull Request #25 has finally been merged (I was late, very late)
