### ISSUE TITLE
Matching of NULL bytes impossible with rstring

### ISSUE THREAD

**Issue by oregano87** [cbonte/haproxy-dconv#19]
For my project it must be possible to check different bytes from \x00 to \xFF via tcp-check expect rstring. But it is not possible to check NULL bytes. Everything after the first NULL byte will be ignored.

My test configuration:
```
tcp-check send-binary 9C00000800870100
tcp-check expect rstring ^\x9a\x00\x00.{5}\x00{13}\x10\x00\x04
```

**Comment by cbonte** [comment]
Hello,
this is not the right place for asking haproxy support. Here, the support is for the converter tool.
Please contact the haproxy mailing list directly.
