### ISSUE TITLE
On the multi-process idle

### ISSUE THREAD

**Issue by GouMingYu** [cbonte/haproxy-dconv#21]
My version is 1.5.4.
I opened a multi-process model, and a number of sock documents, the allocation is as follows:
        nbproc 4 
        ulimit-n 231097
        stats bind-process 1
        stats socket    /tmp/haproxy1.sock level admin
        stats bind-process 2
        stats socket    /tmp/haproxy2.sock level admin
        stats bind-process 3
        stats socket    /tmp/haproxy3.sock level admin
        stats bind-process 4
        stats socket    /tmp/haproxy4.sock level admin

I would like to know, and now take from the sock file to the idle or the whole process is a separate idle idle.

**Comment by cbonte** [comment]
Hi, sorry this is not the right place for haproxy support. Here, it's about the tool to convert the documentation.
You should ask your question directly on the haproxy mailing list.

**Comment by GouMingYu** [comment]
You can provide what Haproxy mailing list address, I can not find addresses.

**Comment by lukastribus** [comment]
You can find it here:
http://www.haproxy.org/#tact

**Comment by GouMingYu** [comment]
thank you very much
