### ISSUE TITLE
Status code -1 with HA-Proxy version 1.5.15

### ISSUE THREAD

**Issue by azilber** [cbonte/haproxy-dconv#22]
I'm seeing the 'status code' as -1 in haproxy logs, whereas the documentation specifies:

"The status code is always 3-digit."

I do see the 'normal' result codes, but I also see a lot of -1's.

**Comment by lukastribus** [comment]
haproxy-dconv is about the documentation converter. Its not about the documentation itself and its not about haproxy.

Please report this to the haproxy mailing list.

**Comment by azilber** [comment]
My bad!
