### ISSUE TITLE
Configuration, 2.5 Exemple, link not working.

### ISSUE THREAD

**Issue by michaudg** [cbonte/haproxy-dconv#24]
In Configuration, section 2, "2.4 Exemples" should be "2.5 Exemples".

**Comment by lukastribus** [comment]
This is a documentation bug in haproxy itself. I just sent a patch, so this should be fixed in the next haproxy release.

Thanks.

**Comment by cbonte** [comment]
Fix available in haproxy 1.8 branch : http://www.haproxy.org/git?p=haproxy.git;a=commitdiff;h=aa83a3144b8eaccfc1d630bc564e294c7c9ebf66
Thank you both !
