### ISSUE TITLE
What is "DSR" ?

### ISSUE THREAD

**Issue by Httqm** [cbonte/haproxy-dconv#28]
The "**What HAProxy is and isn't**" section of the manual (http://cbonte.github.io/haproxy-dconv/2.1/intro.html#3.1) describes things HAProxy does not perform (which is fine). However, one of the sentences there is pretty puzzling for the beginner I am :

> HAProxy is not :
>   - a packet-based load balancer : it will not see IP packets nor UDP datagrams, will not perform NAT or even less DSR.

Ignoring what "DSR" is, DuckDuckGo gave me 2 definitions : 
- https://en.wikipedia.org/wiki/Dynamic_Source_Routing
- https://www.quora.com/Load-Balancing-What-is-DSR

Considering "DSR" is something HAProxy does not perform, I didn't expect it to be referred to further in the manual, but actually found these (possibly obsolete) :
- https://www.haproxy.com/support/technical-notes/an-0053-en-server-configuration-with-an-aloha-in-direct-server-return-mode-dsr/
- https://www.haproxy.com/blog/layer-4-load-balancing-direct-server-return-mode/

Could you, please, clarify this "...will not perform NAT or even less DSR" sentence ?

**Comment by lukastribus** [comment]
This github project is not about haproxy, but about the documentation converter generating the html output on `cbonte.github.io`.

Haproxy support channels are here:

http://www.haproxy.org/#tact


> Considering "DSR" is something HAProxy does not perform, I didn't expect it to be referred to further in the manual.

There is only one manual. Blog posts on the Internet are not a manual.



> https://www.haproxy.com/support/technical-notes/an-0053-en-server-configuration-with-an-aloha-in-direct-server-return-mode-dsr/

This is not about haproxy. This is about the `ALOHA Load-Balancer`, which is unrelated to the Open Source project haproxy.



> https://www.haproxy.com/blog/layer-4-load-balancing-direct-server-return-mode/

This does not suggest that haproxy supports DSR, but it is merely an explanation about what DSR is. In fact the author of the blog posts explains that in the comment section of the post that haproxy does not support DSR.

Also note that haproxy.com is not about the Open Source project Haproxy, but it's a company website (HAProxy Technologies, LLC).



> Could you, please, clarify this "...will not perform NAT or even less DSR" sentence ?

OpenSource Haproxy does not support NAT or DSR, as explained in the manual.

**Comment by Httqm** [comment]
Thank you for your detailed answer.

Sorry for posting this at the wrong place and for (possibly) not making my request clear enough. My question was (and still is) : 
_In the context of the documentation http://cbonte.github.io/haproxy-dconv/2.1/intro.html#3.1 , what does "DSR" stand for ?_

I'll try to get this information from HAproxy's support channels ;-)

**Comment by lukastribus** [comment]
It stands for `Direct Server Return`.
