### ISSUE TITLE
 could not resolve address ipv6

### ISSUE THREAD

**Issue by wpzzz** [cbonte/haproxy-dconv#29]
haproxy2.0.6
 /etc/haproxy/haproxy.cfg
```
frontend ss-in
    timeout client          1m
    bind *:10000-50000
    default_backend ss-out

backend ss-out
    timeout connect         10s
    timeout server          1m
    server server1 2001:470:c:f56::2 maxconn 20480
```

haproxy -D -f /etc/haproxy/haproxy.cfg
: parsing [/etc/haproxy/haproxy.cfg:9] : 'server server1' : could not resolve address '2001:470:c:f56:'.
: Failed to initialize server(s) addr.

if single port will work fine.

**Comment by cbonte** [comment]
This has nothing to do with the haproxy-dconv project (where the goal is to convert the haproxy documentation into html).
If you want some support on how to configure haproxy, please use the haproxy mailing list, and if a bug is really identified, please fill a bug report on the right project : [haproxy](https://github.com/haproxy/haproxy).

Btw, here I don't see any bug except a misconfiguration in your ip:port syntax.
