### ISSUE TITLE
Incorrectly displayed opening single quotes

### ISSUE THREAD

**Issue by mag01** [cbonte/haproxy-dconv#41]
Discussed here: [incorrectly displayed opening single quotes](https://discourse.haproxy.org/t/doc-incorrectly-displayed-opening-single-quotes/7877)

At [HAProxy 2.6 - Configuration Manual](http://docs.haproxy.org/2.6/configuration.html) pretty much all opening (or rather 1st on the line) single quote characters in any examples are shown as `&#x27;` instead of `'`

Examples:

[2.4. Conditional blocks](http://docs.haproxy.org/2.6/configuration.html#2.4)
```
.diag "WTA/2021-05-07: replace &#x27;redirect' with 'return' after switch to 2.4"
```

[7.3.1. Converters - regsub(\<regex\>,\<subst\>[,\<flags\>])](http://docs.haproxy.org/2.6/configuration.html#7.3.1-regsub)
```
http-request set-header x-path "%[hdr(x-path),regsub(&#x27;/+','/','g')]"
http-request set-header x-query "%[query,regsub([?;&]*,&#x27;')]"
http-request redirect location %[url,&#x27;regsub("(foo|bar)([0-9]+)?","\2\1",i)']
```
etc (just search for the `&#x27;` string)

Compare that with the text version of the doc http://www.haproxy.org/download/2.6/doc/configuration.txt where no such issue can be seen.

This also affects older doc versions.

Can this be fixed so it wouldn’t be confusing?

**Comment by cbonte** [comment]
Fixed with https://github.com/cbonte/haproxy-dconv/commit/4decf0b72eff0888195c2353ea149cd969110fe5
